import QtQuick
import Quickshell
import Quickshell.Io
import qs.config

QtObject {
    id: root

    function generate(Colors) {
        if (!Colors) return

        const fmt = (c) => c.toString()
        const toRgba = (c, a) => `rgba(${Math.round(c.r * 255)}, ${Math.round(c.g * 255)}, ${Math.round(c.b * 255)}, ${a})`

        const primary = fmt(Colors.primary)
        const onPrimary = fmt(Colors.overPrimary)
        const primaryContainer = fmt(Colors.primaryContainer)
        const onPrimaryContainer = fmt(Colors.overPrimaryContainer)
        const background = toRgba(Colors.background, Config.theme.srBg.opacity)
        const onBackground = fmt(Colors.overBackground)
        const surface = fmt(Colors.surface)
        const onSurface = fmt(Colors.overSurface)
        const surfaceContainer = fmt(Colors.surfaceContainer)
        const surfaceContainerHigh = fmt(Colors.surfaceContainerHigh)
        const surfaceBright = fmt(Colors.surfaceBright)
        const outline = fmt(Colors.outline)
        const outlineVariant = fmt(Colors.outlineVariant)
        const error = fmt(Colors.error)
        const onError = fmt(Colors.overError)
        const shadow = fmt(Colors.shadow)

        let css = "/* GTK Colors generated by NothingLess — Nothing OS style */\n\n"

        // Core adw-gtk3 / libadwaita color definitions
        css += `@define-color accent_color ${primary};\n`
        css += `@define-color accent_fg_color ${onPrimary};\n`
        css += `@define-color accent_bg_color ${primary};\n`
        css += `@define-color window_bg_color ${background};\n`
        css += `@define-color window_fg_color ${onBackground};\n`
        css += `@define-color headerbar_bg_color ${background};\n`
        css += `@define-color headerbar_fg_color ${onBackground};\n`
        css += `@define-color headerbar_border_color ${outline};\n`
        css += `@define-color headerbar_backdrop_color ${background};\n`
        css += `@define-color headerbar_shade_color ${shadow};\n`
        css += `@define-color popover_bg_color ${surface};\n`
        css += `@define-color popover_fg_color ${onSurface};\n`
        css += `@define-color view_bg_color ${background};\n`
        css += `@define-color view_fg_color ${onBackground};\n`
        css += `@define-color card_bg_color ${surfaceContainer};\n`
        css += `@define-color card_fg_color ${onSurface};\n`
        css += `@define-color dialog_bg_color ${surface};\n`
        css += `@define-color dialog_fg_color ${onSurface};\n`
        css += `@define-color sidebar_bg_color @window_bg_color;\n`
        css += `@define-color sidebar_fg_color @window_fg_color;\n`
        css += `@define-color sidebar_border_color ${outline};\n`
        css += `@define-color sidebar_backdrop_color @window_bg_color;\n`
        css += `@define-color thumbnail_bg_color ${surfaceContainer};\n`
        css += `@define-color thumbnail_fg_color ${onSurface};\n`

        // Semantic colors
        css += `@define-color destructive_color ${error};\n`
        css += `@define-color destructive_fg_color ${onError};\n`
        css += `@define-color destructive_bg_color ${error};\n`
        css += `@define-color success_color #30D158;\n`
        css += `@define-color success_fg_color #0B0B0C;\n`
        css += `@define-color warning_color #FFD60A;\n`
        css += `@define-color warning_fg_color #0B0B0C;\n`
        css += `@define-color error_color ${error};\n`
        css += `@define-color error_fg_color ${onError};\n`
        css += `@define-color error_bg_color ${error};\n`

        // Custom Nothing OS style overrides
        css += `\n/* Nothing OS custom overrides */\n`
        css += `.card { border-radius: 10px; border: 1px solid ${outline}; }\n`
        css += `entry { border-radius: 8px; border: 1px solid ${outline}; }\n`
        css += `entry:focus { border-color: ${primary}; }\n`
        css += `button { border-radius: 6px; }\n`
        css += `button.suggested-action { background: ${primary}; color: ${onPrimary}; }\n`
        css += `button.destructive-action { background: ${error}; color: ${onError}; }\n`
        css += `popover.menu { border-radius: 12px; border: 1px solid ${outline}; }\n`
        css += `tooltip { border-radius: 10px; border: 1px solid ${outline}; }\n`
        css += `scale slider { background: ${primary}; }\n`
        css += `switch:checked { background: ${primary}; }\n`
        css += `progressbar trough { background: ${surfaceContainerHigh}; border-radius: 4px; }\n`
        css += `progressbar progress { background: ${primary}; border-radius: 4px; }\n`
        css += `scrollbar slider { background: ${outline}; border-radius: 4px; min-width: 4px; min-height: 4px; }\n`
        css += `scrollbar slider:hover { background: ${primary}; }\n`
        css += `list { background: transparent; }\n`
        css += `list row { border-radius: 8px; margin: 2px 6px; padding: 8px 12px; }\n`
        css += `list row:hover { background: ${surfaceContainerHigh}; }\n`
        css += `list row:selected { background: ${primaryContainer}; color: ${onPrimaryContainer}; }\n`

        const home = Quickshell.env("HOME")
        const gtk3Dir = home + "/.config/gtk-3.0"
        const gtk4Dir = home + "/.config/gtk-4.0"

        writer.text = css

        // Write to GTK 3/4 and reload theme
        const cmd = `
            mkdir -p "${gtk3Dir}" "${gtk4Dir}" && \\
            echo "${css}" | tee "${gtk3Dir}/gtk.css" "${gtk4Dir}/gtk.css" > /dev/null && \\
            gsettings set org.gnome.desktop.interface gtk-theme "" && \\
            gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3
        `

        writerProcess.command = ["sh", "-c", cmd]
        writerProcess.running = true
    }

    property QtObject writer: QtObject {
        id: writer
        property string text
    }

    property Process writerProcess: Process {
        id: writerProcess
        running: false
        stdout: StdioCollector {
            onStreamFinished: console.log("GtkGenerator: Colors generated.")
        }
        stderr: StdioCollector {
            onStreamFinished: (err) => {
                if (err) console.error("GtkGenerator Error:", err)
            }
        }
    }
Component.onDestruction: {
    writerProcess.stop ? writerProcess.stop() : undefined;
    writerProcess.running !== undefined ? writerProcess.running = false : undefined;
    writerProcess.destroy !== undefined ? writerProcess.destroy() : undefined;
}
}
