#!/usr/bin/env python3
"""
MonitorsWriter - Persist monitor layout to Hyprland config files
Invoked by NothingLess's MonitorsWriter QML service

Usage:
  monitors_writer.py sync [--json <path>] [--conf <path>] [--lua <path>]
  monitors_writer.py write <conf_path> <lua_path> [--data <json_string>]

Reads monitor state from either:
  - JSON file (--json), or
  - JSON string (--data), or
  - `hyprctl monitors -j` (no args)

Writes:
  - monitors.conf (Hyprland .conf format)
  - monitors.lua (Hyprland V2 Lua format)
  - Creates backups
  - Applies changes live via hyprctl dispatch
"""

import json
import os
import shutil
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path


def get_config_dir():
    """Get Hyprland config dir"""
    xdg_config = os.environ.get("XDG_CONFIG_HOME",
                                 os.path.expanduser("~/.config"))
    return os.path.join(xdg_config, "hypr")


def get_monitors_data(json_path=None, json_data=None):
    """Get monitor data from JSON file, string, or hyprctl"""
    if json_path and os.path.isfile(json_path):
        with open(json_path, "r") as f:
            return json.load(f)
    elif json_data:
        return json.loads(json_data)
    else:
        result = subprocess.run(
            ["hyprctl", "monitors", "-j"],
            capture_output=True, text=True, timeout=5
        )
        if result.returncode == 0 and result.stdout.strip():
            return json.loads(result.stdout)
        # Fall back to axctl
        result = subprocess.run(
            ["axctl", "monitor", "list"],
            capture_output=True, text=True, timeout=5
        )
        if result.returncode == 0 and result.stdout.strip():
            return json.loads(result.stdout)
        return []


def normalize_monitors(monitors_data):
    """
    Normalize monitor data from various sources into a standard format.
    Handles hyprctl, axctl, and custom data formats.
    """
    normalized = []

    for m in monitors_data:
        meta = m.get("metadata", {})
        entry = {
            "name": m.get("name", ""),
            "width": m.get("width", 0),
            "height": m.get("height", 0),
            "x": m.get("x", meta.get("x", 0)),
            "y": m.get("y", meta.get("y", 0)),
            "scale": m.get("scale", 1.0),
            "refreshRate": m.get("refreshRate", m.get("refresh_rate", 60)),
            "transform": m.get("transform", meta.get("transform", 0)),
            "enabled": m.get("enabled", True),
            "bitdepth": m.get("bitdepth", m.get("bit_depth", 0)),
            "mirror": m.get("mirror", ""),
            "vrr": m.get("vrr", 0),
            "description": m.get("description", ""),
        }
        normalized.append(entry)

    return normalized


def generate_conf_lines(monitors):
    """Generate Hyprland .conf format lines"""
    transforms = ["normal", "90", "180", "270",
                  "flipped", "flipped-90", "flipped-180", "flipped-270"]

    lines = [
        "# Generated by NothingLess on {}. Do not edit manually.".format(
            datetime.now().strftime("%Y-%m-%d at %H:%M:%S")),
        "",
    ]

    for m in monitors:
        name = m["name"]
        if not m["enabled"]:
            lines.append(f"monitor={name},disable")
            continue

        mode = f"{m['width']}x{m['height']}@{m['refreshRate']:.2f}Hz"
        pos = f"{m['x']}x{m['y']}"

        line = f"monitor={name},{mode},{pos},{m['scale']}"

        if m.get("bitdepth", 0) >= 10:
            line += ",bitdepth,10"

        if m.get("mirror"):
            line += f",mirror,{m['mirror']}"

        lines.append(line)

        if m.get("transform", 0) != 0:
            lines.append(f"monitor={name},transform,{m['transform']}")

        if m.get("vrr", 0):
            lines.append(f"monitor={name},vrr,{m['vrr']}")

    return lines


def generate_lua_lines(monitors):
    """Generate Hyprland V2 Lua format lines"""
    lines = [
        "-- Generated by NothingLess on {}. Do not edit manually.".format(
            datetime.now().strftime("%Y-%m-%d at %H:%M:%S")),
        "",
    ]

    for m in monitors:
        name = m["name"]

        if not m["enabled"]:
            lines.append(f"hl.monitor({{\n    output = \"{name}\",\n    disabled = true\n}})")
            lines.append("")
            continue

        mode = f"{m['width']}x{m['height']}@{m['refreshRate']:.2f}Hz"
        pos = f"{m['x']}x{m['y']}"

        lua_lines = [f"hl.monitor({{"]
        lua_lines.append(f'    output = "{name}",')
        lua_lines.append(f'    mode = "{mode}",')
        lua_lines.append(f'    position = "{pos}",')
        lua_lines.append(f'    scale = {m["scale"]}')

        if m.get("bitdepth", 0) >= 10:
            lua_lines.append(f"    bitdepth = 10")

        if m.get("mirror"):
            lua_lines.append(f'    mirror = "{m["mirror"]}"')

        if m.get("transform", 0) != 0:
            lua_lines.append(f"    transform = {m['transform']}")

        if m.get("vrr", 0):
            lua_lines.append(f"    vrr = {m['vrr']}")

        lua_lines.append("})")
        lua_lines.append("")

        lines.extend(lua_lines)

    return lines


def apply_live(monitors):
    """Apply monitor changes via hyprctl reload (reads monitors.conf)"""
    try:
        subprocess.run(["hyprctl", "reload"], capture_output=True, timeout=5)
        print("[OK] Applied via hyprctl reload")
    except Exception as e:
        print(f"[WARN] hyprctl reload failed: {e}", file=sys.stderr)
        for m in monitors:
            name = m.get("name", "")
            if not name or not m.get("enabled", True):
                continue
            mode = f"{m['width']}x{m['height']}@{m['refreshRate']:.2f}Hz"
            pos = f"{m['x']}x{m['y']}"
            try:
                subprocess.run(
                    ["hyprctl", "dispatch", f"monitor {name},{mode},{pos},{m['scale']}"],
                    capture_output=True, timeout=3
                )
            except Exception as e:
                print(f"[WARN] Failed to apply {name}: {e}", file=sys.stderr)

def write_conf(lines, path):
    """Write .conf file with backup"""
    path = os.path.expanduser(path)
    backup = path + ".bak"

    if os.path.isfile(path):
        shutil.copy2(path, backup)

    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"[OK] Wrote {path} ({len(lines)} lines)")


def write_lua(lines, path):
    """Write .lua file with backup"""
    path = os.path.expanduser(path)
    backup = path + ".bak"

    if os.path.isfile(path):
        shutil.copy2(path, backup)

    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"[OK] Wrote {path} ({len(lines)} lines)")


def cmd_sync(args):
    """Read monitors and write configs"""
    config_dir = get_config_dir()
    conf_path = args.conf or os.path.join(config_dir, "monitors.conf")
    lua_path = args.lua or os.path.join(config_dir, "monitors.lua")

    monitors_data = get_monitors_data(json_path=args.json, json_data=args.data)
    monitors = normalize_monitors(monitors_data)

    if not monitors:
        print("[WARN] No monitors detected", file=sys.stderr)
        return 1

    print(f"[INFO] Syncing {len(monitors)} monitors...")

    conf_lines = generate_conf_lines(monitors)
    lua_lines = generate_lua_lines(monitors)

    os.makedirs(os.path.dirname(os.path.expanduser(conf_path)), exist_ok=True)
    os.makedirs(os.path.dirname(os.path.expanduser(lua_path)), exist_ok=True)

    write_conf(conf_lines, conf_path)
    write_lua(lua_lines, lua_path)

    if not args.no_apply:
        print("[INFO] Applying live...")
        apply_live(monitors)

    print("[OK] Monitor sync complete")
    return 0


def cmd_write(args):
    """Write specific data to config files (from QML)"""
    monitors_data = get_monitors_data(json_data=args.data)
    monitors = normalize_monitors(monitors_data)

    if not monitors:
        print("[WARN] No monitor data provided", file=sys.stderr)
        return 1

    conf_path = os.path.expanduser(args.conf_path)
    lua_path = os.path.expanduser(args.lua_path)

    conf_lines = generate_conf_lines(monitors)
    lua_lines = generate_lua_lines(monitors)

    os.makedirs(os.path.dirname(conf_path), exist_ok=True)
    os.makedirs(os.path.dirname(lua_path), exist_ok=True)

    write_conf(conf_lines, conf_path)
    write_lua(lua_lines, lua_path)

    apply_live(monitors)

    print("[OK] Write complete")
    return 0


def main():
    import argparse

    parser = argparse.ArgumentParser(
        description="NothingLess MonitorsWriter - Persist monitor config"
    )

    subparsers = parser.add_subparsers(dest="command")

    # sync command
    sync_parser = subparsers.add_parser("sync", help="Sync monitors from hyprctl")
    sync_parser.add_argument("--json", help="JSON file with monitor data")
    sync_parser.add_argument("--conf", help="Path to monitors.conf (default: ~/.config/hypr/monitors.conf)")
    sync_parser.add_argument("--lua", help="Path to monitors.lua (default: ~/.config/hypr/monitors.lua)")
    sync_parser.add_argument("--data", help="JSON string with monitor data")
    sync_parser.add_argument("--no-apply", action="store_true", help="Skip live application")

    # write command
    write_parser = subparsers.add_parser("write", help="Write monitor data to files")
    write_parser.add_argument("conf_path", help="Path to monitors.conf")
    write_parser.add_argument("lua_path", help="Path to monitors.lua")
    write_parser.add_argument("--data", required=True, help="JSON string with monitor data")

    args = parser.parse_args()

    if args.command == "sync":
        return cmd_sync(args)
    elif args.command == "write":
        return cmd_write(args)
    else:
        parser.print_help()
        return 0


if __name__ == "__main__":
    sys.exit(main())
