#!/usr/bin/env bash
# Wrapper para nothingless-resize.py
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}" )")" && pwd)"
exec python3 "${SCRIPT_DIR}/nothingless-resize.py" "$@"
