.pragma library

var data = {
    "barMode": "extended",
    "position": "top",
    "launcherIcon": "",
    "launcherIconTint": true,
    "launcherIconFullTint": true,
    "launcherIconSize": 24,
    "pillStyle": "default",
    "screenList": [],
    "enableFirefoxPlayer": false,
    "enableChromiumPlayer": false,
    "barColor": [["surface", 0.0]],
    "frameEnabled": false,
    "frameThickness": 6,
    "pinnedOnStartup": true,
    "hoverToReveal": true,
    "hoverRegionHeight": 2,
    "showPinButton": true,
    "availableOnFullscreen": false,
    "use12hFormat": false,
    "containBar": false,
    "keepBarShadow": false,
    "keepBarBorder": false,
    "hiddenIcons": [],
    "taskTrayEnabled": true,
    "taskTrayShowToggle": true,
    "taskTrayAlwaysVisible": []
}
